# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    # TODO: test report

    - name: Build with Gradle Wrapper
      run: |
          cd vulnerable-web-app
          ./gradlew build

    - name: Deploy and run on EC2 instance
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.CRABPEM }}
        SOURCE: "./vulnerable-web-app/build/libs/vulnerable-web-app-1.0-SNAPSHOT.jar"
        REMOTE_HOST: "ec2-13-60-29-54.eu-north-1.compute.amazonaws.com"
        REMOTE_USER: "ec2-user"
        TARGET: "/home/ec2-user/crab"
        SCRIPT_AFTER: |
          java -jar /home/ec2-user/crab/vulnerable-web-app-1.0-SNAPSHOT.jar
          

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.CRABPEM }}

    - name: Copy JAR file to EC2
      run: |
        scp -o StrictHostKeyChecking=no ./vulnerable-web-app/build/libs/vulnerable-web-app-1.0-SNAPSHOT.jar ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }}:/home/${{ secrets.AWS_USER }}/vulnerable-web-app.jar

    - name: Start Java Application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} 'nohup java -jar /home/${{ secrets.AWS_USER }}/vulnerable-web-app.jar > /dev/null 2>&1 &'